[package]
name = "preexplorer"
version = "0.1.0"
authors = ["Raimundo Saona <rasa200@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
failure = "0.1"
num-traits = "0.2"

[dev-dependencies]
ndarray = "0.13.0"
